### ISSUE TITLE
Gradle Build Fails - Repository Not Found - plugin nebula.netflixoss', version: '2.2.7'

### ISSUE THREAD

**Issue by harshasharma** [Netflix/Priam#401]
Hi,

Using gradlew build command fails with the following exception. Please advise.

C:\Vigneshwaran Official\March Downloads\Priam-master\Priam-master>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Vigneshwaran Official\March Downloads\Priam-master\Priam-master\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '2.2.7']
> repository not found: C:\Vigneshwaran Official\March Downloads\Priam-master\Priam-master

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.634 secs

WITH STACKTRACE 

C:\Vigneshwaran Official\March Downloads\Priam-master\Priam-master>gradlew build
 --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Vigneshwaran Official\March Downloads\Priam-master\Priam-master\b
uild.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version:
 '2.2.7']
> repository not found: C:\Vigneshwaran Official\March Downloads\Priam-master\Pr
iam-master

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying pl
ugin request [id: 'nebula.netflixoss', version: '2.2.7']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPl
ugin(DefaultPluginRequestApplicator.java:168)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPl
ugins(DefaultPluginRequestApplicator.java:124)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.
apply(DefaultScriptPluginFactory.java:131)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
riptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
riptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.eva
luate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
ifecycleProjectEvaluator.java:59)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:504)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:83)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(Task
PathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuil
dConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not f
ound: C:\Vigneshwaran Official\March Downloads\Priam-master\Priam-master
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilde
r.java:575)
        at org.eclipse.jgit.api.Git.open(Git.java:113)
        at org.eclipse.jgit.api.Git.open(Git.java:97)
        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy:223)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
        at org.ajoberstar.grgit.Grgit$open.call(Unknown Source)
        at nebula.plugin.release.ReleasePlugin$_apply_closure2.doCall(ReleasePlu
gin.groovy:43)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy:42)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(
DefaultPluginContainer.java:188)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInter
nal(DefaultPluginContainer.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultP
luginContainer.java:107)
        at org.gradle.api.plugins.PluginContainer$apply.call(Unknown Source)
        at nebula.plugin.netflixossproject.NetflixOssProjectPlugin.apply(Netflix
OssProjectPlugin.groovy:54)
        at nebula.plugin.netflixossproject.NetflixOssProjectPlugin.apply(Netflix
OssProjectPlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(
DefaultPluginContainer.java:188)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInter
nal(DefaultPluginContainer.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultP
luginContainer.java:103)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$4.run(D
efaultPluginRequestApplicator.java:126)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPl
ugin(DefaultPluginRequestApplicator.java:156)
        ... 36 more

BUILD FAILED

Total time: 3.07 secs

**Comment by rspieldenner** [comment]
Are you on the internet? Can you reach plugins.gradle.org? Which JDK? And
you are using the checked in gradlew?

Can you use the

plugins {
  id '<plugin>' version '<version>'
}

to resolve any plugins?

**Comment by harshasharma** [comment]
Hi Rob,

Thank you for your response!!

Yes. I am on the internet.. when I ran the gradlew build the first time, it took a good 15-20 mins to download all dependencies and stopped at the error.. Since then, everytime I run the build command it directly fails immediately (as the other packages are already downloaded). 

Tried on two computers: JDK Version: 1.8.0_20 and 1.7.

We just downloaded the current Master Zip... and ran the 'gradlew build' command from inside the extracted zip file. 

Yes we tried with 2.2.7 (default) and 2.2.3 and both gave the same error.

**Comment by rspieldenner** [comment]
I'm able to resolve with idk 1.7.0_75 and 1.8.0_31.

Things to try:

The following will invalidate the cache
./gradlew clean build --refresh-dependencies

Delete our plugins if the download was corrupted
rm -rf
~/.gradle/caches/modules-2/files-2.1/com.netflix.nebula/gradle-netflixoss-project-plugin

Check if you have any buildSrc or files in ~/.gradle/init.d that is setting
up buildscript resolution

**Comment by harshasharma** [comment]
Hi Rob,

I am running this from Windows.. so i ran the equivalent of the above linux commands on my machine.

Trying to Invalidate the cache fails as well (same error):

gradlew clean build --refresh-dependencies

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\hsharma\Desktop\Projects-India\Revury\Priam-master\build.gr
adle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version:
 '2.2.7']
> repository not found: C:\Users\hsharma\Desktop\Projects-India\Revury\Priam-mas
ter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 3 mins 42.861 secs



Next, I deleted the plugin from the equivalent path : C:\Users\hsharma\.gradle\caches\modules-2\files-2.1\com.netflix.nebula\gradle-netflixoss-project-plugin (windows equivalent)

I didnt have any init.d file/setting under C:\Users\hsharma\.gradle\ (windows equivalent)   I reran the build command and it seems to have downloaded the plugin again but then immediately failed again..


gradlew build
Download http://plugins.gradle.org/m2/com/netflix/nebula/gradle-netflixoss-proje
ct-plugin/2.2.7/gradle-netflixoss-project-plugin-2.2.7.jar

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\hsharma\Desktop\Projects-India\Revury\Priam-master\build.gr
adle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version:
 '2.2.7']
> repository not found: C:\Users\hsharma\Desktop\Projects-India\Revury\Priam-mas
ter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 8.211 secs

**Comment by rspieldenner** [comment]
Ah I think I see it in the stacktrace now. The netflixoss plugin expects to
be run from a git clone. It explicitly looks for the .git directory so that
it can use git tags to do version calculations.

**Comment by harshasharma** [comment]
Thanks Rob,

Anything specifically that we should do to workaround this?

**Comment by rspieldenner** [comment]
We want to calculate version off git, so have people clone instead of
downloading the zip.

**Comment by gregturn** [comment]
@rspieldenner I ran into this same issue when using a "nebulafied" project used inside "git submodules". git submodules. In this situation, there is a .git file, but it contains this:

```
gitdir: ../.git/modules/clouddriver
```
pointing to where the actual git details are kept.

I tried overriding with "-Pgit.root" pointing at the root folder, but it doesn't appear good enough.

**Comment by IndeCy** [comment]
download with git clone instead of zip , and i gradle build successfully
