### ISSUE TITLE
Getting 'ContainerResponse.mapMappableContainerException' exception

### ISSUE THREAD

**Issue by MonicaBansal** [Netflix/Priam#403]
HI,
I am getting this exception when I am running the code with 10 Threads running simultaneously and each thread execute the same 10 times. Please help me in finding out the reason for the same.

JerseyPubSub.java:94 - at this line I m broadcasting the message.
broadcaster.broadcast("abc");

 SEVERE [http-nio-48080-exec-36] com.sun.jersey.spi.cont
ainer.ContainerResponse.mapMappableContainerException The RuntimeException could
 not be mapped to a response, re-throwing to the HTTP container
 java.lang.NullPointerException
        at org.atmosphere.samples.pubsub.JerseyPubSub.SendDataToUUID(JerseyPubSu
b.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMe
thodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMeth
odDispatchProvider$VoidOutInvoker._dispatch(AbstractResourceMethodDispatchProvid
er.java:167)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDi
spatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethod
Rule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHa
ndPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(Resourc
eClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHa
ndPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(R
ootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequ
est(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequ
est(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleReque
st(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleReque
st(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponen
t.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(Servlet
Container.java:540)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(Servlet
Container.java:715)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.atmosphere.util.AtmosphereFilterChain.doFilter(AtmosphereFilterCh
ain.java:135)
        at org.atmosphere.util.AtmosphereFilterChain.invokeFilterChain(Atmospher
eFilterChain.java:96)
        at org.atmosphere.handler.ReflectorServletProcessor$FilterChainServletWr
apper.service(ReflectorServletProcessor.java:317)
        at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorS
ervletProcessor.java:160)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor
.java:197)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProces
sor.java:104)
        at org.atmosphere.container.Servlet30CometSupport.service(Servlet30Comet
Support.java:66)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFrame
work.java:2069)
        at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:21
1)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52
)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:503)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:136)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAcce
ssLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:526)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1078)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:655)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.pr
ocess(Http11NioProtocol.java:222)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoin
t.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.lang.Thread.run(Thread.java:724)

**Comment by timiblossom** [comment]
I am sorry as this is your container's issue and this is not the appropriate place for this question.
