### ISSUE TITLE
Priam with Cassandra 2.1.6

### ISSUE THREAD

**Issue by pencilmouse** [Netflix/Priam#409]
Hi,
 I am trying to upgrade our Cassandra to 2.1.6 version and used the latest Priam version from maven (2.0.7). When I started Priam, Priam logs says the cassandra started and does not report any error but when i check cassandra log I find the following issue. Is it due to new version of cassandra? or something different? Let me know if you need more logs.

ERROR 15:07:02 Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml. Please remove properties [multithreaded_compaction, memtable_total_space_in_mb, in_memory_compaction_limit_in_mb] from your cassandra.yaml
	at org.apache.cassandra.config.YamlConfigurationLoader$MissingPropertiesChecker.check(YamlConfigurationLoader.java:162) ~[apache-cassandra-2.1.6.jar:2.1.6]
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:115) ~[apache-cassandra-2.1.6.jar:2.1.6]
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:84) ~[apache-cassandra-2.1.6.jar:2.1.6]
	at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:161) ~[apache-cassandra-2.1.6.jar:2.1.6]
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:136) ~[apache-cassandra-2.1.6.jar:2.1.6]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:164) [apache-cassandra-2.1.6.jar:2.1.6]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:536) [apache-cassandra-2.1.6.jar:2.1.6]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:625) [apache-cassandra-2.1.6.jar:2.1.6]
Invalid yaml. Please remove properties [multithreaded_compaction, memtable_total_space_in_mb, in_memory_compaction_limit_in_mb] from your cassandra.yaml
Fatal configuration error; unable to start. See log for stacktrace.

**Comment by timiblossom** [comment]
Hi pencilmouse ,

We currently support C* 2.0.x only.

**Comment by nirshtern5** [comment]
What is the timeline for supporting C* 2.1.x ?

**Comment by pdehlke** [comment]
@jhohertz has a version that seems to work with 2.1, up to 2.1.4 at least (I have not tested anything later)

https://github.com/jhohertz/Priam/tree/staging_2.1

**Comment by jhohertz** [comment]
Just a warning that my branch has not tracked mainline development since Oct 2014, and I am not presently working on it. That said you may be able to cherry pick some commits from Oct 10, 2014, which is when I worked around the yaml config issues.

**Comment by sciclon** [comment]
I needed to upgrade Cassandra to 2.1.x then I came across with this thread, I don't see in the current branches anything which mentions the use of Cassandra above 2.0.9.

Looks like if I want to use 2.1.x I will need to stop using Priam, is any other alternative.

Thanks!

**Comment by pankajbhanu** [comment]
Hi, I wanted to know what is the latest version of cassandra supported by priam. I couldn't find it anywhere in the wiki.

Thanks

**Comment by tulumvinh** [comment]
The latest C* version supported by Priam is 2.1, using Priam branch 3.x.
