### ISSUE TITLE
Failed to obtain startup  priam, can not start yet. :BUILD faild 

### ISSUE THREAD

**Issue by llehad** [Netflix/Priam#415]
build faild when i use ./gradlew build .
This the priam.log file. I cannot resolve errors.

    TestRestore. testNoSnapshots 
    TestRestore. testRestore
    TestRestore. testRestoreFromDiffCluster
    TestRestore. testRestoreLatest

Unable to delete file: target/data/Keyspace1/Standard1/snapshots/201508071159/Keyspace1-Standard1-ia-7-Data.db
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1643)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1200)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1634)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1200)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1634)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1200)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1634)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1200)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1634)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1268)
	at com.netflix.priam.utils.SystemUtils.cleanupDir(SystemUtils.java:79)
	at com.netflix.priam.backup.Restore.restore(Restore.java:120)
	at com.netflix.priam.backup.TestRestore.testNoSnapshots(TestRestore.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
-----------------
  CassandraAdminTest. parseGossipInfo

org.codehaus.jettison.json.JSONException: JSONObject["  SCHEMA"] not found.

Can anyone help me?

**Comment by autocracy** [comment]
Kind of a +1 to this. Building off master:
com.netflix.priam.resources.CassandraAdminTest > parseGossipInfo FAILED
    org.codehaus.jettison.json.JSONException at CassandraAdminTest.java:39

com.netflix.priam.resources.BackupServletTest > restore_withDateRange FAILED
    java.lang.IllegalArgumentException at BackupServletTest.java:120

com.netflix.priam.resources.BackupServletTest > restore_maximal FAILED
    java.lang.IllegalArgumentException at BackupServletTest.java:307

98 tests completed, 3 failed, 7 skipped
:priam:test FAILED

**Comment by jezard** [comment]
@scottmcmaster  this worked for me thank you!

**Comment by tulumvinh** [comment]
Hello all, validated and merged @scottmcmaster pull request.

Thanks Scoot.
