### ISSUE TITLE
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.2.3']

### ISSUE THREAD

**Issue by sandeepkanabar** [Netflix/Priam#458]
**Update: This only occurs if trying to build the ZIP file. If you clone from git and build, it succeeds but if you download the zip file and build, it fails.**

I'm trying to build Priam in my CentOS box which has java version 1.8.0_40:

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

I'm getting the below exception when I try to build:
 Cannot set property 'defaultVersionStrategy' on null object

Here is the full stacktrace.

[root@single-node-es-1 Priam-3.0.7]# ./gradlew build --stacktrace
Git repository not found at /vagrant/Priam-3.0.7 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.

FAILURE: Build failed with an exception.
- Where:
  Build file '/vagrant/Priam-3.0.7/build.gradle' line: 2
- What went wrong:
  An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.2.3']
  
  > Failed to apply plugin [id 'nebula.netflixoss']
  > *\* Cannot set property 'defaultVersionStrategy' on null object**
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.2.3']
  at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:178)
  at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:130)
  at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:126)
  at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
  at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
  at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
  at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:510)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90)
  at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
  at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
  at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
  at org.gradle.internal.Factories$1.create(Factories.java:22)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
  at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
  at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
  at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
  at org.gradle.launcher.Main.doAction(Main.java:33)
  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
  at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'nebula.netflixoss']
  at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
  at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
  at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$5.run(DefaultPluginRequestApplicator.java:132)
  at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:166)
  ... 49 more
  Caused by: java.lang.NullPointerException: Cannot set property 'defaultVersionStrategy' on null object
  at nebula.plugin.netflixossproject.NetflixOssProjectPlugin$_apply_closure1.doCall(NetflixOssProjectPlugin.groovy:55)
  at nebula.plugin.netflixossproject.NetflixOssProjectPlugin.apply(NetflixOssProjectPlugin.groovy:54)
  at nebula.plugin.netflixossproject.NetflixOssProjectPlugin.apply(NetflixOssProjectPlugin.groovy)
  at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
  at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
  at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
  ... 52 more

BUILD FAILED

Total time: 4.661 secs

Could someone please help?

Thanks,
Sandeep

**Comment by sandeepkanabar** [comment]
I cloned the project from git and was able to build it successfully. Earlier I was trying to build the source from the zip file Priam-3.0.7.zip that my colleague shared with me. He's in a different timezone and I'm awaiting an update from him.

Thanks.

**Comment by ipapapa** [comment]
@sandeepkanabar did you try to use `git.root` as the error message says? The error message says:

`Git repository not found at /vagrant/Priam-3.0.7 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.`

**Comment by sandeepkanabar** [comment]
@ipapapa Thanks a ton. In this case, the .git folder wasn't existing. And that explained the cause of the error message.

**Comment by 9731756162** [comment]
@ipapapa how to use git.root as a gradle property to specify a different directory

**Comment by proclamo** [comment]
I'm working with the 3.x branch and cloned the repo and I have the same issue. I can't build the project. Anybody knows how to fix or a workaround?

**Comment by arunagrawal84** [comment]
@proclamo are you still having issues with 3.x branch?

**Comment by proclamo** [comment]
@arunagrawal84 now it works! thanks a lot :-)
